services:

  nginx:
    image: nginx:1.23.4-alpine

    ports:
      - 2002:2002
      - 80:80
      - 443:443
    build:
      context: ./nginx
      dockerfile: Dockerfile
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt
    depends_on:
      - backend-asgi
      - backend-wsgi
      - frontend

  redis:
    image: redis:7.2-rc1-alpine

    expose:
      - 6379
    volumes:
      - ./redis:/data
    restart: always
    healthcheck:
      test: [ "CMD", "redis-cli", "--raw", "incr", "ping" ]

  database:
    image: postgres:15-alpine

    expose:
      - 5432

    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}

    volumes:
      - ./data/drtrottoir:/var/lib/postgresql/data/

    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U django -d drtrottoir" ]
      interval: 5s
      timeout: 5s
      retries: 5


  backend-wsgi:
    build:
      context: ./backend
      dockerfile: Dockerfile

    environment:
      ENVIRONMENT: ${ENVIRONMENT}
      DJANGO_SECRET_KEY: ${DJANGO_SECRET_KEY}
      SECRET_EMAIL_USER: ${SECRET_EMAIL_USER}
      SECRET_EMAIL_USER_PSWD: ${SECRET_EMAIL_USER_PSWD}

    command: [ "gunicorn", "config.wsgi:application", "-b", "localhost:8000" ]

    expose:
      - 8000

    volumes:
      - ./backend:/app/backend-wsgi

    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8000" ]
      interval: 1m
      timeout: 10s
      retries: 3

    depends_on:
      database:
        condition: service_healthy
      redis:
        condition: service_healthy

  backend-asgi:
    build:
      context: ./backend
      dockerfile: Dockerfile

    environment:
      ENVIRONMENT: ${ENVIRONMENT}
      DJANGO_SECRET_KEY: ${DJANGO_SECRET_KEY}
      SECRET_EMAIL_USER: ${SECRET_EMAIL_USER}
      SECRET_EMAIL_USER_PSWD: ${SECRET_EMAIL_USER_PSWD}
      # TODO: strangely the methods in wsgi work without this, check why this isn't the case for asgi
      DJANGO_SETTINGS_MODULE: config.settings

    command: [ "daphne", "config.asgi:application", "-b", "localhost", "-p", "9000" ]

    expose:
      - 9000

    healthcheck:
      test: [ "CMD", "curl", "--fail", "http://localhost:9000" ]
      interval: 1m
      timeout: 10s
      retries: 3

    volumes:
      - ./backend:/app/backend-asgi

    depends_on:
      # this dependency to backend-wsgi makes sure we don't loop infinitely
      backend-wsgi:
        condition: service_started
      database:
        condition: service_healthy
      redis:
        condition: service_healthy

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        ENVIRONMENT: ${ENVIRONMENT}

    environment:
      ENVIRONMENT: ${ENVIRONMENT}

    expose:
      - 3000

    volumes:
      - ./frontend/pages:/app/frontend/pages
      - ./frontend/components:/app/frontend/components
      - ./frontend/lib:/app/frontend/lib
      - ./frontend/public:/app/frontend/public
      - ./frontend/styles:/app/frontend/styles
      - ./frontend/locales:/app/frontend/locales

    depends_on:
      backend-wsgi:
        condition: service_started
      backend-asgi:
        condition: service_started