services:
  reverseproxy:
    image: reverseproxy
    ports:
      - 2002:2002
      - 80:80
      - 443:443
    build:
      context: ./nginx
      dockerfile: Dockerfile
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt
    restart: always

  # database
  web:
    image: postgres:15-alpine
    ports:
      - '5432:5432'

    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=django
      - POSTGRES_DB=drtrottoir

    volumes:
      - ./data/drtrottoir:/var/lib/postgresql/data/

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile

    volumes:
      - ./frontend/pages:/app/frontend/pages
      - ./frontend/components:/app/frontend/components
      - ./frontend/lib:/app/frontend/lib
      - ./frontend/public:/app/frontend/public
      - ./frontend/styles:/app/frontend/styles
      - ./frontend/locales:/app/frontend/locales

    depends_on:
      - backend
      - reverseproxy

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile

    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=django
      - POSTGRES_DB=drtrottoir

    volumes:
      - ./backend:/app/backend

    mem_limit: 512m
    mem_reservation: 128m
    cpus: 0.5

    depends_on:
      - web