# Generated by Django 4.1.7 on 2023-03-08 09:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentatbuildingontour',
            name='building',
        ),
        migrations.RemoveField(
            model_name='studentatbuildingontour',
            name='tour',
        ),
        migrations.AddField(
            model_name='studentatbuildingontour',
            name='building_on_tour',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.buildingontour'),
        ),
        migrations.AlterField(
            model_name='buildingontour',
            name='index',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='studentatbuildingontour',
            name='student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='user',
            name='region',
            field=models.ManyToManyField(blank=True, to='base.region'),
        ),
    ]
