# Generated by Django 4.1.7 on 2023-03-17 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('template', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='EmailWhitelist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(error_messages={'unique': 'This email is already on the whitelist.'}, max_length=254, unique=True, verbose_name='email address')),
                ('verification_code', models.CharField(error_messages={'unique': 'This verification code already exists.'}, max_length=128, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='building',
            name='public_id',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.DeleteModel(
            name='BuildingURL',
        ),
        migrations.AddConstraint(
            model_name='emailtemplate',
            constraint=models.UniqueConstraint(models.F('name'), name='unique_template_name', violation_error_message='The name for this template already exists.'),
        ),
    ]
