# Generated by Django 4.1.7 on 2023-03-30 22:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='buildingontour',
            name='unique_index_on_tour',
        ),
    ]
