# Generated by Django 4.1.7 on 2023-04-19 13:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0001_initial"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="pictureofremark",
            name="unique_picture_with_remark",
        ),
        migrations.AddField(
            model_name="pictureofremark",
            name="hash",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="buildingcomment",
            name="building",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to="base.building"
            ),
        ),
        migrations.AlterField(
            model_name="lobby",
            name="email",
            field=models.EmailField(
                error_messages={"unique": "This email is already in the lobby."},
                max_length=254,
                unique=True,
                verbose_name="email address",
            ),
        ),
        migrations.AlterField(
            model_name="region",
            name="region",
            field=models.CharField(error_messages={"unique": "This region already exists"}, max_length=40, unique=True),
        ),
        migrations.AddConstraint(
            model_name="buildingontour",
            constraint=models.UniqueConstraint(
                models.F("index"),
                models.F("tour"),
                name="unique_index_on_tour",
                violation_error_message="This index is already in use.",
            ),
        ),
        migrations.AddConstraint(
            model_name="pictureofremark",
            constraint=models.UniqueConstraint(
                models.F("hash"),
                models.F("remark_at_building"),
                name="unique_picture_with_remark",
                violation_error_message="The building already has this upload.",
            ),
        ),
    ]
