# Generated by Django 4.1.7 on 2023-03-10 18:03

from django.db import migrations, models
import django.db.models.functions.text


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='building',
            name='address_unique',
        ),
        migrations.RemoveConstraint(
            model_name='buildingontour',
            name='unique_index_on_tour',
        ),
        migrations.RemoveConstraint(
            model_name='buildingontour',
            name='unique_building_on_tour',
        ),
        migrations.RemoveConstraint(
            model_name='garbagecollection',
            name='garbage_collection_unique',
        ),
        migrations.RemoveConstraint(
            model_name='manual',
            name='unique_manual',
        ),
        migrations.RemoveConstraint(
            model_name='picturebuilding',
            name='unique_picture_building',
        ),
        migrations.RemoveConstraint(
            model_name='studentatbuildingontour',
            name='unique_student_at_building_on_tour',
        ),
        migrations.RemoveConstraint(
            model_name='tour',
            name='unique_tour',
        ),
        migrations.AlterField(
            model_name='buildingurl',
            name='url',
            field=models.CharField(error_messages={'unique': 'Deze URL bestaat al.'}, max_length=2048, unique=True),
        ),
        migrations.AlterField(
            model_name='region',
            name='region',
            field=models.CharField(error_messages={'unique': 'Deze regio bestaat al.'}, max_length=40, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(error_messages={'unique': 'Er is al een gebruiker met deze email.'}, max_length=254, unique=True, verbose_name='email address'),
        ),
        migrations.AddConstraint(
            model_name='building',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('city'), django.db.models.functions.text.Lower('street'), django.db.models.functions.text.Lower('postal_code'), django.db.models.functions.text.Lower('house_number'), name='address_unique', violation_error_message='Er is al een gebouw met dit adres.'),
        ),
        migrations.AddConstraint(
            model_name='buildingontour',
            constraint=models.UniqueConstraint(models.F('index'), models.F('tour'), name='unique_index_on_tour', violation_error_message='De ronde heeft al een gebouw op deze index.'),
        ),
        migrations.AddConstraint(
            model_name='buildingontour',
            constraint=models.UniqueConstraint(models.F('building'), models.F('tour'), name='unique_building_on_tour', violation_error_message='Dit gebouw komt al voor op deze ronde.'),
        ),
        migrations.AddConstraint(
            model_name='garbagecollection',
            constraint=models.UniqueConstraint(models.F('building'), django.db.models.functions.text.Lower('garbage_type'), models.F('date'), name='garbage_collection_unique', violation_error_message='Dit soort afval wordt al op deze dag bij het gebouw afgehaald.'),
        ),
        migrations.AddConstraint(
            model_name='manual',
            constraint=models.UniqueConstraint(models.F('building_id'), models.F('version_number'), name='unique_manual', violation_error_message='Het gebouw heeft al een handleiding met dit versienummer.'),
        ),
        migrations.AddConstraint(
            model_name='picturebuilding',
            constraint=models.UniqueConstraint(models.F('building'), django.db.models.functions.text.Lower('picture_name'), django.db.models.functions.text.Lower('description'), models.F('timestamp'), name='unique_picture_building', violation_error_message='Het gebouw heeft al hetzelfde soort foto op hetzelfde tijdstip.'),
        ),
        migrations.AddConstraint(
            model_name='studentatbuildingontour',
            constraint=models.UniqueConstraint(models.F('building_on_tour'), models.F('date'), models.F('student'), name='unique_student_at_building_on_tour', violation_error_message='De student doet op deze dag al deze ronde.'),
        ),
        migrations.AddConstraint(
            model_name='tour',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('name'), models.F('region'), name='unique_tour', violation_error_message='Er bestaat al een ronde met dezelfde naam in de regio.'),
        ),
    ]
