# Generated by Django 4.2.1 on 2023-05-14 13:39

import base.models
from django.db import migrations, models
import django.db.models.functions.text


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='remarkatbuilding',
            name='unique_remark_for_building',
        ),
        migrations.AlterField(
            model_name='pictureofremark',
            name='picture',
            field=models.ImageField(upload_to=base.models.get_file_path_image),
        ),
        migrations.AddConstraint(
            model_name='remarkatbuilding',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('remark'), models.F('building'), models.F('student_on_tour'), models.F('timestamp'), models.F('type'), name='unique_remark_for_building', violation_error_message='This remark was already uploaded to this building by this student on the tour.'),
        ),
    ]
