# Generated by Django 4.1.7 on 2023-03-09 00:02

from django.db import migrations, models
import django.db.models.functions.text


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='building',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='buildingontour',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='garbagecollection',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='manual',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='building',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='manual',
            name='version_number',
            field=models.PositiveIntegerField(),
        ),
        migrations.AddConstraint(
            model_name='building',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('city'), django.db.models.functions.text.Lower('street'), django.db.models.functions.text.Lower('postal_code'), django.db.models.functions.text.Lower('house_number'), name='address_unique'),
        ),
        migrations.AddConstraint(
            model_name='buildingontour',
            constraint=models.UniqueConstraint(models.F('index'), models.F('tour'), name='unique_building_on_tour'),
        ),
        migrations.AddConstraint(
            model_name='garbagecollection',
            constraint=models.UniqueConstraint(models.F('building'), django.db.models.functions.text.Lower('garbage_type'), models.F('date'), name='garbage_collection_unique'),
        ),
        migrations.AddConstraint(
            model_name='manual',
            constraint=models.UniqueConstraint(models.F('building_id'), models.F('version_number'), name='unique_manual'),
        ),
    ]
