# Generated by Django 4.1.7 on 2023-03-10 21:00

from django.db import migrations, models
import django.db.models.functions.text


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_remove_building_address_unique_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='picturebuilding',
            name='unique_picture_building',
        ),
        migrations.RemoveConstraint(
            model_name='studentatbuildingontour',
            name='unique_student_at_building_on_tour',
        ),
        migrations.RemoveField(
            model_name='manual',
            name='filename',
        ),
        migrations.RemoveField(
            model_name='picturebuilding',
            name='picture_name',
        ),
        migrations.AddField(
            model_name='manual',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='building_manuals/'),
        ),
        migrations.AddField(
            model_name='picturebuilding',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='building_pictures/'),
        ),
        migrations.AddConstraint(
            model_name='picturebuilding',
            constraint=models.UniqueConstraint(models.F('building'), django.db.models.functions.text.Lower('picture'), django.db.models.functions.text.Lower('description'), models.F('timestamp'), name='unique_picture_building', violation_error_message='Het gebouw heeft al hetzelfde soort foto op hetzelfde tijdstip.'),
        ),
        migrations.AddConstraint(
            model_name='studentatbuildingontour',
            constraint=models.UniqueConstraint(models.F('building_on_tour'), models.F('date'), models.F('student'), name='unique_student_at_building_on_tour', violation_error_message='De student doet op deze dag al de ronde.'),
        ),
    ]
