# Generated by Django 4.1.7 on 2023-04-01 11:34

from django.db import migrations, models
import django.db.models.functions.text


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_pictureofremark_remarkatbuilding_studentontour_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='remarkatbuilding',
            name='unique_remark_for_building',
        ),
        migrations.AddConstraint(
            model_name='remarkatbuilding',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('remark'), models.F('building_on_tour'), models.F('timestamp'), name='unique_remark_for_building', violation_error_message='This remark was already uploaded to this building.'),
        ),
    ]
