# Generated by Django 4.1.7 on 2023-03-11 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_rename_firstname_user_first_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='buildingurl',
            old_name='firstname_resident',
            new_name='first_name_resident',
        ),
        migrations.RenameField(
            model_name='buildingurl',
            old_name='lastname_resident',
            new_name='last_name_resident',
        ),
        migrations.RemoveField(
            model_name='buildingurl',
            name='url',
        ),
        migrations.AlterField(
            model_name='buildingurl',
            name='id',
            field=models.BigIntegerField(primary_key=True, serialize=False),
        ),
    ]
