# Generated by Django 4.1.7 on 2023-03-03 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_auto_20230227_1454'),
    ]

    operations = [
        migrations.AddField(
            model_name='gebouw',
            name='duur',
            field=models.TimeField(default='00:00'),
        ),
    ]
