# Generated by Django 4.1.7 on 2023-02-26 09:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gebouw',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stad', models.CharField(max_length=40)),
                ('postcode', models.CharField(max_length=10)),
                ('straat', models.CharField(max_length=60)),
                ('huisnummer', models.CharField(max_length=10)),
                ('klantennummer', models.CharField(blank=True, max_length=40, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Regio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('regio', models.CharField(max_length=40, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Ronde',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naam', models.CharField(max_length=40)),
                ('modified_at', models.DateTimeField()),
                ('regio_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='database.regio')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=254, unique=True)),
                ('voornaam', models.CharField(max_length=40)),
                ('achternaam', models.CharField(max_length=40)),
                ('telefoon', models.CharField(max_length=20)),
                ('rol', models.CharField(choices=[('ST', 'Student'), ('SS', 'Superstudent'), ('AD', 'Admin'), ('SY', 'Syndicus')], max_length=2)),
                ('regio', models.ManyToManyField(to='database.regio')),
            ],
        ),
        migrations.CreateModel(
            name='StudentBijGebouwOpRonde',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datum', models.DateField()),
                ('gebouw_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.gebouw')),
                ('ronde', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.ronde')),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='database.user')),
            ],
        ),
        migrations.AddField(
            model_name='gebouw',
            name='regio_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='database.regio'),
        ),
        migrations.AddField(
            model_name='gebouw',
            name='syndicus_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='database.user'),
        ),
        migrations.CreateModel(
            name='FotoGebouw',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto_naam', models.CharField(max_length=2048)),
                ('beschrijving', models.TextField(blank=True, null=True)),
                ('tijdstip', models.DateTimeField()),
                ('type', models.CharField(choices=[('AA', 'Aankomst'), ('BI', 'Binnen'), ('VE', 'Vertrek'), ('OP', 'Opmerking')], max_length=2)),
                ('gebouw_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.gebouw')),
            ],
        ),
        migrations.CreateModel(
            name='Vuilophaling',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datum', models.DateField()),
                ('soort_vuil', models.CharField(choices=[('GFT', 'GFT'), ('GLS', 'Glas'), ('GRF', 'Grof vuil'), ('KER', 'Kerstbomen'), ('PAP', 'Papier'), ('PMD', 'PMD'), ('RES', 'Restafval')], max_length=3)),
                ('gebouw_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.gebouw')),
            ],
            options={
                'unique_together': {('gebouw_id', 'soort_vuil', 'datum')},
            },
        ),
        migrations.CreateModel(
            name='Handleiding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('versienummer', models.IntegerField()),
                ('bestandsnaam', models.CharField(max_length=2048)),
                ('gebouw_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.gebouw')),
            ],
            options={
                'unique_together': {('gebouw_id', 'versienummer')},
            },
        ),
        migrations.CreateModel(
            name='GebouwURL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=2048)),
                ('voornaam_inwoner', models.CharField(max_length=40)),
                ('achternaam_inwoner', models.CharField(max_length=40)),
                ('gebouw_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.gebouw')),
            ],
            options={
                'unique_together': {('url', 'gebouw_id')},
            },
        ),
        migrations.CreateModel(
            name='GebouwOpRonde',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.IntegerField()),
                ('gebouw_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.gebouw')),
                ('ronde', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.ronde')),
            ],
            options={
                'unique_together': {('index', 'ronde')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='gebouw',
            unique_together={('stad', 'postcode', 'straat', 'huisnummer')},
        ),
    ]
