name: Code Formatting and Linting

on:
  push:
    branches: [ '**' ]
    paths:
      - '**.py'
      - '**.js'
  pull_request:
    branches:
      - main
      - develop
    paths:
      - '**.py'
      - '**.js'

jobs:
  format_and_lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # using `black` for Python
      - name: Format Python code
        if: git diff --name-only | grep -E '\.py$'
        uses: docker://python:3.8
        with:
          args: |
            sh -c "pip install black && black ."

      # using `flake8` for Python
      - name: Lint Python code
        if: git diff --name-only | grep -E '\.py$'
        id: python-lint
        uses: docker://python:3.8
        with:
          args: |
            sh -c "pip install flake8 && flake8 ."


      # using `prettier` for JavaScript
      - name: Format JavaScript code
        if: git diff --name-only | grep -E '\.js$'
        uses: docker://node:16
        with:
          args: |
            sh -c "npm install --global prettier && prettier --write '**/*.js'"

      # using `eslint` for JavaScript
      - name: Lint JavaScript code
        if: git diff --name-only | grep -E '\.js$'
        id: javascript-lint
        uses: docker://node:16
        with:
          args: |
            sh -c "npm install --global eslint && eslint '**/*.js'"

      # if either one has a linting error when executing a pull request, give an error and don't allow the request
      - name: Check for linting errors
        if: ${{ github.event_name == 'pull_request' }}
        run: |
          if [ ${{ steps.python-lint.outcome }} == 'failure' -o ${{ steps.javascript-lint.outcome }} == 'failure' ]; then
            echo "Linting of code failed. Please fix the errors before merging the pull request."
            exit 1
          fi

      # if no linting errors, format code and finalize request
      - name: Commit changes
        if: ${{ success() }}
        run: |
          git config --global user.email "group4@selab2.com"
          git config --global user.name "Group 4"
          if git diff --name-only | grep -E '\.py$|\.js$'; then
            git add .
            git commit -m "Auto-format and lint code"
            git push
          fi