name: Django Translations

on:
  pull_request:
    branches:
      - main
      - develop
    paths:
      - 'backend/**'

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install -r backend/requirements.txt
          sudo apt-get update
          sudo apt install gettext

      - name: Make and compile messages
        run: |
          cd backend
          django-admin makemessages --all
          django-admin compilemessages

      - name: Commit translation changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Auto compile translation messages"

