name: Format and Lint Code Base


on:
  push:
    branches: [ '**' ]
#      - main
#      - develop

jobs:
  build:
    name: Format and Lint Code Base
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
          fetch-depth: 0

      # using `black` for Python
      - name: Format Python code
        uses: rickstaa/action-black@v1.3.1
        id: action_black
        with:
          black_args: "."


      # using `prettier` for JavaScript
      - name: Format JavaScript code
        uses: creyD/prettier_action@v4.3
        with:
          prettier_options: --write **/*.{js,tsx}
          same_commit: true

      - name: Commit Python changes
        if: steps.action_black.outputs.is_formatted == 'true'
        run: |
          git config --global user.email "group4@selab2.com"
          git config --global user.name "Group 4"
          git pull
          git commit --amend --no-edit
          git push origin -f

      - name: Lint Code Base
        uses: github/super-linter@v4.10.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VALIDATE_ALL_CODEBASE: false
          DEFAULT_BRANCH: main
          VALIDATE_YAML: false