name: Code Formatting and Linting SQL

on:
  # all branches when pushing, only pull request for the main branch
  push:
    branches: ['**']
    paths:
      - '**.sql'
  pull_request:
    branches: [main]

jobs:
  format_and_lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # using `sqlparse`
      - name: Format SQL code
        uses: docker://python:3.8
        with:
          args: |
            sh -c "pip install sqlparse && find . -name '*.sql' -type f -exec sh -c 'sql-formatter -f {} > {}.new && mv {}.new {}' \;"

      # using `sqlfluff`
      - name: Lint SQL code
        id: sql-lint
        uses: docker://python:3.8
        with:
          args: |
            sh -c "pip install sqlfluff && sqlfluff lint --dialect postgres"

      # if either one has a linting error when executing a pull request, give an error and don't allow the request
      - name: Check for linting errors
        if: ${{ github.event_name == 'pull_request' }}
        run: |
          if [ ${{ steps.sql-lint.outcome }} == 'failure' ]; then
            echo "Linting of SQL files failed. Please fix the errors before merging the pull request."
            exit 1
          fi

      # if no linting errors, format code and finalize request
      - name: Commit changes
        if: ${{ success() }}
        run: |
          git config --global user.email "group4@selab2.com"
          git config --global user.name "Group 4"
          if git diff --name-only | grep -E '\.sql$'; then
            git add .
            git commit -m "Auto-format and lint SQL code"
            git push
          fi