name: Format Code Base

on:
  push:
    branches: [ '**' ]
#      - main
#      - develop

jobs:
  build:
    name: Format Code Base
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
          fetch-depth: 0

      # using `black` for Python
      - name: Format Python code
        uses: rickstaa/action-black@v1.3.1
        id: action_black
        with:
          black_args: "."


      # using `prettier` for JavaScript
      - name: Format JavaScript code
        uses: creyD/prettier_action@v4.3
        with:
          prettier_options: --write **/*.{js,tsx}
          commit_message: "Auto formatted JS code"
          only_changed: true
          github_token: ${{ secrets.GITHUB_TOKEN }}


      - name: Commit changes
        if: steps.action_black.outputs.is_formatted == 'true'
        run: |
          git config --global user.email "group4@selab2.com"
          git config --global user.name "Group 4"
          git pull
          git add **/*.py
          git commit -m "Auto formatted Python code"
          git push