name: Format Code Base

on:
  pull_request:
    branches:
      - main
      - develop

jobs:
  format:
    name: Format Code Base
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
          fetch-depth: 0

      # using `black` for Python
      - name: Format Python code
        uses: rickstaa/action-black@v1.3.1
        id: action_black
        with:
          black_args: ". --line-length 120"

      # using `prettier` for JavaScript
      - name: Format JavaScript code
        uses: creyD/prettier_action@v4.3
        with:
          prettier_options: --print-width 120 --write **/*.{js,tsx}
          commit_message: "Auto formatted code"
          only_changed: true
          github_token: ${{ secrets.GITHUB_TOKEN }}