name: Lint Code Base

on:
  push:
    branches: [ '**' ]
#      - main
#      - develop

jobs:
  lint:
    name: Lint Code Base
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Lint Code Base
        uses: github/super-linter@v4.10.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          OUTPUT_DETAILS: detailed
          VALIDATE_ALL_CODEBASE: false
          DEFAULT_BRANCH: main
